version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    labels:
      - product/invisible
      - dependencies
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
  - package-ecosystem: pip
    directory: "/scripts"
    schedule:
      interval: daily
    labels:
      - product/invisible
      - dependencies
